export const SET_IP = 'SET_IP';
export const SET_PORT = 'SET_PORT';
export const SET_REFRESH_TIME = 'SET_REFRESH_TIME';

export const SET_MEDIA_PLAYER_DATA = 'SET_MEDIA_PLAYER_DATA';
export const SET_SYNC_ENABLED = 'SET_SYNC_ENABLED';

export const SEND_COMMAND = 'SEND_COMMAND';
export const SEND_COMMAND_SUCCESS = 'SEND_COMMAND_SUCCESS';
export const SEND_COMMAND_FAIL = 'SEND_COMMAND_FAIL';
